apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv
spec:
    accessModes: 
    - ReadWriteOnce
    storageClassName: ssd
    capacity:
        storage: 20Gi
    persistentVolumeReclaimPoliy: Retain
    gcePersistentDisk:
        pdName: uber-disk
