apiVersion: v1
kind: Namespace
metadata:
    name: acg-ns
---
apiVersion: v1
kind: Service
metadata:
    namespace: acg-ns
    name: acg-lb
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: acg-stress
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: acg-web
    namespace: acg-ns
    labels:
        app: acg-stress
spec:
    selector:
        matchLabels:
            app: acg-stress
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    template:
        metadata:
            labels:
                app: acg-stress
        spec:
            containers:
            - image: k8s.gcr.io/hpa-example
              name: stresser
              ports:
              - containerPort: 80
              resources:
                requests:
                    cpu: 0.2
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: acg-hpa
    namespace: acg-ns
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: acg-web
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
